{% set version = "0.1.12" %}

package:
  name: htmlmin
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/htmlmin/htmlmin-{{ version }}.tar.gz
  sha256: 50c1ef4630374a5d723900096a961cff426dff46b48f34d194a81bbe14eca178

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - htmlmin = htmlmin.command:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - htmlmin
  commands:
    - htmlmin --help

about:
  home: https://htmlmin.readthedocs.org/en/latest/
  dev_url: https://github.com/mankyd/htmlmin/
  doc_url: https://htmlmin.readthedocs.org/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A configurable HTML Minifier with safety features
  description: A configurable HTML Minifier with safety features

extra:
  recipe-maintainers:
    - daf
